language: swift
osx_image: xcode12
env:
  global:
  - FRAMEWORK_NAME=AWSAppSync
xcode_workspace: AWSAppSyncClient.xcworkspace
xcode_scheme: AWSAppSync
before_install:
- openssl aes-256-cbc -K $encrypted_6919a533707f_key -iv $encrypted_6919a533707f_iv
  -in AWSAppSyncIntegrationTests/appsync_test_credentials.json.enc
  -out AWSAppSyncIntegrationTests/appsync_test_credentials.json
  -d
- brew update
- brew outdated carthage || brew upgrade carthage
- gem install cocoapods -v '1.9.3'
before_deploy:
- bash ./build-support/carthage-build.sh build --no-skip-current
- bash ./build-support/carthage-build.sh archive $FRAMEWORK_NAME
script:
- xcodebuild -quiet -workspace AWSAppSyncClient.xcworkspace -scheme AWSAppSync build test -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest'
deploy:
- provider: releases
  api_key:
    secure: "HsoXU87LNgkUnxbvSVcSU5/FVSjYQMTU/su2mmXQAm4WHbTt21zTywvYx1kzHFP6TT7N+V+kheQNaL92ZHjYmTPbX3q2R+rVa474JMaPgZocJtaBizTYam5q9Rv3I5Gijh2PHOsIRH4FnUDHxvggr3EVdb5jQDIU8H5L4us1ywVCKZvMlZheREYqUuVd27TU8WfTSvwKbe2CaV8hvfl54TyuIBUfJ9ssDqFojYiq0bb8YmHzlsrI8QcWJiVcwZRvFCH8hBPN3l5qV07y2Y3ZDbeptww7VXvm0dCcx+gXBGIoj2F7s42gav5q6Dr677kvNtEndKR8ZiQtZTJDdOm9WdLNdK0rCcazy5Q09Z+4tsqQKHPSw7apJp6+hBRsfrOxENx6QQUYFiE+RqVBCX45uH7qYK0bM4a2sa2YMGHO/Oi4RLnpgKcKNFE5W5Di8u2AgIyX4cAiZHL9bX5D+imhjK3NoPPSW14CZ2dDCOW8MdkxeYgIgXLcSK7etazxzdCUOstfi0neJyCcgtWWJt67fkn6f+25bvDED5fJter8Bo1hP9sLlhigD2Y7L5TRJ2dl3CJMFRWYp4dN6yEwJNGbLZr47r8M4LRIhphi/S5jyQFbDAgGx4VK4lLK1nhh+3blTzzG/xJC3DlCD8w/qhxBMZMBrKQ4PfPWY9vfDIDnano="
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
   repo: awslabs/aws-mobile-appsync-sdk-ios
   tags: true
- provider: script
  script: bash ./build-support/cocoapods_release.sh
  on:
    repo: awslabs/aws-mobile-appsync-sdk-ios
    tags: true
